version: '3.8'

services:
  web:
    build: .
    container_name: pl_platform_app
    env_file:
    - ./env/postgre-db.env
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: my_postgres_db
    env_file:
    - ./env/postgre-db.env
    ports:
      - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: