name: Build & push image and update infrastructure

on:
  release:
    types: [created]

jobs:
  build-and-push:
    # This job buil and push the updated docker image
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set-up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PW }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pl_platform_backend:${{ github.event.release.tag_name }}
        platforms: linux/amd64,linux/arm64/v8

  update-infrastructure:
    # This job will update the infrastructure repository, managed by ArgoCD, to update minikube cluster infrastructure
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'lscope/pl_platform_infrastructure'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Update YAML file
      run: sed -i 's|lucascopelliti/pl_platform_backend:[^ ]*|lucascopelliti/pl_platform_backend:${{ github.event.release.tag_name }}|' infrastructure/app/pl_platform-deployment.yml

    - name: Commit and Push Changes
      run: |
        git config user.name 'lscope'
        git config user.email 'l.scope98@gmail.com'
        git add infrastructure/app/pl_platform-deployment.yml
        git commit -m "[refactor] Update image tag to ${{ github.event.release.tag_name }}"
        git push
