name: Push docker image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 8
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PW }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/bid_decision_engine:python${{ matrix.python-version }}-${{ github.event.release.tag_name }}
        build-args: PYTHON_VERSION=${{ matrix.python-version }}

  update-onboarding-image:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'bidcompany/bid-onboarding-env'
        token: ${{ secrets.GH_ACTIONS_READ_WRITE_TOKEN }}

    - name: Update devcontainer.json
      run: sed -i 's|breakindocker/bid_decision_engine:python3.[^ ]*|breakindocker/bid_decision_engine:python3.11-${{ github.event.release.tag_name }}|' .devcontainer/devcontainer.json

    - name: Commit and Push Changes
      run: |
        git config user.name 'lucascopelliti'
        git config user.email 'luca.scopelliti@bidcompany.it'
        git add .devcontainer/devcontainer.json
        git commit -m "[refactor] Update bid_decision_engine base image tag to ${{ github.event.release.tag_name }}"
        git push
