name: CI

on: 
  push:
    branches:
      - "dev"
    paths-ignore:
      - 'README.md'
      - '.mypy.ini'
      - '.gitignore'
      - '.github/*'
      - 'docs/*'
      - '.dockerignore'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'README.Docker.md'
      - 'LICENSE'
      - '.devcontainer/*'
  pull_request:
    branches:
      - "dev"
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Test with pyTest
      run: pytest -v --cov=./bid_decision_engine/ --cov-report=xml:./coverage/report.xml --cov-report=html:./coverage/report

    - name: Check coverage
      run: |
        coverage report -m
        coverage xml
        if [ $(coverage report | grep 'TOTAL' | awk '{print $4}') -lt 90 ]; then
          echo "Coverage less than 90%"
          exit 1
        fi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/report.xml
        fail_ci_if_error: true

